### ISSUE TITLE
Your newest version doesn't work

### ISSUE THREAD

**Issue by TerableCoder** [Sunpui/Endless-Crafting#11]
Fixed version here: https://github.com/TerableCoder/Endless-Crafting

**Comment by TerableCoder** [comment]
Works for me and others, NA Caali proxy.

**Comment by ghost** [comment]
Attempted again, Original statement still stands. Have you tested the code you put out fully?
Like it crafts, but once it gets to the point of consuming a Crafting Cure it does not do it.

**Comment by TerableCoder** [comment]
That's what was happening when I used the code here :c 
I tested mine and it works for crafting and for using the pp pot then continuing to craft.

**Comment by ghost** [comment]
Hmm Strange. 
-Bubbles Versions get the the point of fully running out of PP- then glitching out after consuming a cure and not continuing on to craft the last item.
-Yours get to the point, that i fully run out of PP - and fails to pop a cure. Then a system message pops  up "Unable to craft due to low production points.(you wont see this message in video, system messages are not enabled on that chat tab)" [https://streamable.com/381dh](https://streamable.com/381dh)

-

**Comment by TerableCoder** [comment]
https://streamable.com/ey33b
Not sure why it doesn't work for you. Any ideas?

**Comment by TerableCoder** [comment]
I figured it out, my S_FATIGABILITY_POINT.3 is labeled
int32 unk
int32 fatigability
int32 current

When I change it to 

int32 unk
int32 current
int32 fatigability

and replace the word "current" in my version with "fatigability" it works the same. This was probably the issue you're facing. I'll make a config file with a setting for it.

**Comment by TerableCoder** [comment]
Now it works for either packet labeling.

**Comment by ghost** [comment]
Hmm. I shall change my def file for   S_FATIGABILITY_POINT.3 
I was using the set up provided to me by bubble.
int32 unk
int32 max
int32 fatigability


> _...Oh god i ran out of stuff to craft testing._

**Comment by ghost** [comment]
./)w(\\. I think that was it. More of a me error, then code error it seems. Protocol was mapped differently.

**Comment by TerableCoder** [comment]
Nice!

**Comment by Sunpui** [comment]
I've done a pull request
https://github.com/caali-hackerman/tera-data/pull/8/commits/b419e0195b34db436b4472ef158ce28997524210
this is my S_FATIGABILITY_POINT.3. I don't see why we would need to change the name from fatigability to current.

**Comment by TerableCoder** [comment]
I forgot my friend gave me a bunch of .defs a while ago, so I thought this labeling was the default. Your labeling makes more sense.
