### ISSUE TITLE
`S_UPDATE_PRODUCE` is undefined, opcode outdated

### ISSUE THREAD

**Issue by ghost** [Sunpui/Endless-Crafting#7]
`S_UPDATE_PRODUCE` has no def in tera-data/protocol. NA received a patch a few days ago, so your readme `S_FATIGABILITY_POINT` opcode is outdated.

**Comment by Sunpui** [comment]
S_UPDATE_PRODUCE has a def https://github.com/meishuu/tera-data/blob/master/protocol/S_UPDATE_PRODUCE.2.def it just won't show up on github because the list is too long.
Opcode is in meishuu's tera-data S_FATIGABILITY_POINT = 48294
